// Code generated by shimgen; DO NOT EDIT.
// Deprecated: use github.com/merlindrones/rclgo/pkg/msgs/action_msgs/msg instead.
package msg

import pub "github.com/merlindrones/rclgo/pkg/msgs/action_msgs/msg"

type CGoalInfo = pub.CGoalInfo
type CGoalInfo__Sequence = pub.CGoalInfo__Sequence
type CGoalStatus = pub.CGoalStatus
type CGoalStatusArray = pub.CGoalStatusArray
type CGoalStatusArray__Sequence = pub.CGoalStatusArray__Sequence
type CGoalStatus__Sequence = pub.CGoalStatus__Sequence
type GoalInfo = pub.GoalInfo
type GoalInfoPublisher = pub.GoalInfoPublisher
type GoalInfoSubscription = pub.GoalInfoSubscription
type GoalInfoSubscriptionCallback = pub.GoalInfoSubscriptionCallback
type GoalStatus = pub.GoalStatus
type GoalStatusArray = pub.GoalStatusArray
type GoalStatusArrayPublisher = pub.GoalStatusArrayPublisher
type GoalStatusArraySubscription = pub.GoalStatusArraySubscription
type GoalStatusArraySubscriptionCallback = pub.GoalStatusArraySubscriptionCallback
type GoalStatusPublisher = pub.GoalStatusPublisher
type GoalStatusSubscription = pub.GoalStatusSubscription
type GoalStatusSubscriptionCallback = pub.GoalStatusSubscriptionCallback

const GoalStatus_STATUS_ABORTED = pub.GoalStatus_STATUS_ABORTED
const GoalStatus_STATUS_ACCEPTED = pub.GoalStatus_STATUS_ACCEPTED
const GoalStatus_STATUS_CANCELED = pub.GoalStatus_STATUS_CANCELED
const GoalStatus_STATUS_CANCELING = pub.GoalStatus_STATUS_CANCELING
const GoalStatus_STATUS_EXECUTING = pub.GoalStatus_STATUS_EXECUTING
const GoalStatus_STATUS_SUCCEEDED = pub.GoalStatus_STATUS_SUCCEEDED
const GoalStatus_STATUS_UNKNOWN = pub.GoalStatus_STATUS_UNKNOWN

var GoalInfoTypeSupport = pub.GoalInfoTypeSupport
var GoalStatusArrayTypeSupport = pub.GoalStatusArrayTypeSupport
var GoalStatusTypeSupport = pub.GoalStatusTypeSupport

var CloneGoalInfoSlice = pub.CloneGoalInfoSlice
var CloneGoalStatusArraySlice = pub.CloneGoalStatusArraySlice
var CloneGoalStatusSlice = pub.CloneGoalStatusSlice
var GoalInfo__Array_to_C = pub.GoalInfo__Array_to_C
var GoalInfo__Array_to_Go = pub.GoalInfo__Array_to_Go
var GoalInfo__Sequence_to_C = pub.GoalInfo__Sequence_to_C
var GoalInfo__Sequence_to_Go = pub.GoalInfo__Sequence_to_Go
var GoalStatusArray__Array_to_C = pub.GoalStatusArray__Array_to_C
var GoalStatusArray__Array_to_Go = pub.GoalStatusArray__Array_to_Go
var GoalStatusArray__Sequence_to_C = pub.GoalStatusArray__Sequence_to_C
var GoalStatusArray__Sequence_to_Go = pub.GoalStatusArray__Sequence_to_Go
var GoalStatus__Array_to_C = pub.GoalStatus__Array_to_C
var GoalStatus__Array_to_Go = pub.GoalStatus__Array_to_Go
var GoalStatus__Sequence_to_C = pub.GoalStatus__Sequence_to_C
var GoalStatus__Sequence_to_Go = pub.GoalStatus__Sequence_to_Go
var NewGoalInfo = pub.NewGoalInfo
var NewGoalInfoPublisher = pub.NewGoalInfoPublisher
var NewGoalInfoSubscription = pub.NewGoalInfoSubscription
var NewGoalStatus = pub.NewGoalStatus
var NewGoalStatusArray = pub.NewGoalStatusArray
var NewGoalStatusArrayPublisher = pub.NewGoalStatusArrayPublisher
var NewGoalStatusArraySubscription = pub.NewGoalStatusArraySubscription
var NewGoalStatusPublisher = pub.NewGoalStatusPublisher
var NewGoalStatusSubscription = pub.NewGoalStatusSubscription
