// Code generated by shimgen; DO NOT EDIT.
// Deprecated: use github.com/merlindrones/rclgo/pkg/msgs/builtin_interfaces/msg instead.
package msg

import pub "github.com/merlindrones/rclgo/pkg/msgs/builtin_interfaces/msg"

type CDuration = pub.CDuration
type CDuration__Sequence = pub.CDuration__Sequence
type CTime = pub.CTime
type CTime__Sequence = pub.CTime__Sequence
type Duration = pub.Duration
type DurationPublisher = pub.DurationPublisher
type DurationSubscription = pub.DurationSubscription
type DurationSubscriptionCallback = pub.DurationSubscriptionCallback
type Time = pub.Time
type TimePublisher = pub.TimePublisher
type TimeSubscription = pub.TimeSubscription
type TimeSubscriptionCallback = pub.TimeSubscriptionCallback

var DurationTypeSupport = pub.DurationTypeSupport
var TimeTypeSupport = pub.TimeTypeSupport

var CloneDurationSlice = pub.CloneDurationSlice
var CloneTimeSlice = pub.CloneTimeSlice
var Duration__Array_to_C = pub.Duration__Array_to_C
var Duration__Array_to_Go = pub.Duration__Array_to_Go
var Duration__Sequence_to_C = pub.Duration__Sequence_to_C
var Duration__Sequence_to_Go = pub.Duration__Sequence_to_Go
var NewDuration = pub.NewDuration
var NewDurationPublisher = pub.NewDurationPublisher
var NewDurationSubscription = pub.NewDurationSubscription
var NewTime = pub.NewTime
var NewTimePublisher = pub.NewTimePublisher
var NewTimeSubscription = pub.NewTimeSubscription
var Time__Array_to_C = pub.Time__Array_to_C
var Time__Array_to_Go = pub.Time__Array_to_Go
var Time__Sequence_to_C = pub.Time__Sequence_to_C
var Time__Sequence_to_Go = pub.Time__Sequence_to_Go
