// Code generated by rclgo-gen. DO NOT EDIT.

package test

/*
#cgo LDFLAGS: "-L/opt/ros/humble/lib" "-Wl,-rpath=/opt/ros/humble/lib"
#cgo CFLAGS: "-I/opt/ros/humble/include/builtin_interfaces"
#cgo CFLAGS: "-I/opt/ros/humble/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/opt/ros/humble/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/opt/ros/humble/include/sensor_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/std_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/test_msgs"

#cgo LDFLAGS: "-L/home/dave/Git/merlin/rclgo/lib" "-Wl,-rpath=/home/dave/Git/merlin/rclgo/lib"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/builtin_interfaces"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/sensor_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/std_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/test_msgs"

#cgo LDFLAGS: -lrcl -lrcl_interfaces__rosidl_typesupport_c -lrcutils
#cgo LDFLAGS: -lrmw_implementation -lrosidl_runtime_c -lrosidl_typesupport_c
#cgo LDFLAGS: -lsensor_msgs__rosidl_generator_c -lsensor_msgs__rosidl_typesupport_c
#cgo LDFLAGS: -lstd_msgs__rosidl_generator_c -lstd_msgs__rosidl_typesupport_c
#cgo LDFLAGS: -ltest_msgs__rosidl_generator_c -ltest_msgs__rosidl_typesupport_c
*/
import "C"
