// Code generated by rclgo-gen. DO NOT EDIT.

package lifecycle_msgs_msg

import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <lifecycle_msgs/msg/transition_description.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("lifecycle_msgs/TransitionDescription", TransitionDescriptionTypeSupport)
	typemap.RegisterMessage("lifecycle_msgs/msg/TransitionDescription", TransitionDescriptionTypeSupport)
}

type TransitionDescription struct {
	Transition Transition `yaml:"transition"`  // The transition id and label of this description.
	StartState State      `yaml:"start_state"` // The current state from which this transition transitions.
	GoalState  State      `yaml:"goal_state"`  // The desired target state of this transition.
}

// NewTransitionDescription creates a new TransitionDescription with default values.
func NewTransitionDescription() *TransitionDescription {
	self := TransitionDescription{}
	self.SetDefaults()
	return &self
}

func (t *TransitionDescription) Clone() *TransitionDescription {
	c := &TransitionDescription{}
	c.Transition = *t.Transition.Clone()
	c.StartState = *t.StartState.Clone()
	c.GoalState = *t.GoalState.Clone()
	return c
}

func (t *TransitionDescription) CloneMsg() types.Message {
	return t.Clone()
}

func (t *TransitionDescription) SetDefaults() {
	t.Transition.SetDefaults()
	t.StartState.SetDefaults()
	t.GoalState.SetDefaults()
}

func (t *TransitionDescription) GetTypeSupport() types.MessageTypeSupport {
	return TransitionDescriptionTypeSupport
}

// TransitionDescriptionPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type TransitionDescriptionPublisher struct {
	*rclgo.Publisher
}

// NewTransitionDescriptionPublisher creates and returns a new publisher for the
// TransitionDescription
func NewTransitionDescriptionPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*TransitionDescriptionPublisher, error) {
	pub, err := node.NewPublisher(topic_name, TransitionDescriptionTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &TransitionDescriptionPublisher{pub}, nil
}

func (p *TransitionDescriptionPublisher) Publish(msg *TransitionDescription) error {
	return p.Publisher.Publish(msg)
}

// TransitionDescriptionSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type TransitionDescriptionSubscription struct {
	*rclgo.Subscription
}

// TransitionDescriptionSubscriptionCallback type is used to provide a subscription
// handler function for a TransitionDescriptionSubscription.
type TransitionDescriptionSubscriptionCallback func(msg *TransitionDescription, info *rclgo.MessageInfo, err error)

// NewTransitionDescriptionSubscription creates and returns a new subscription for the
// TransitionDescription
func NewTransitionDescriptionSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback TransitionDescriptionSubscriptionCallback) (*TransitionDescriptionSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg TransitionDescription
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, TransitionDescriptionTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &TransitionDescriptionSubscription{sub}, nil
}

func (s *TransitionDescriptionSubscription) TakeMessage(out *TransitionDescription) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneTransitionDescriptionSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneTransitionDescriptionSlice(dst, src []TransitionDescription) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var TransitionDescriptionTypeSupport types.MessageTypeSupport = _TransitionDescriptionTypeSupport{}

type _TransitionDescriptionTypeSupport struct{}

func (t _TransitionDescriptionTypeSupport) New() types.Message {
	return NewTransitionDescription()
}

func (t _TransitionDescriptionTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.lifecycle_msgs__msg__TransitionDescription
	return (unsafe.Pointer)(C.lifecycle_msgs__msg__TransitionDescription__create())
}

func (t _TransitionDescriptionTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.lifecycle_msgs__msg__TransitionDescription__destroy((*C.lifecycle_msgs__msg__TransitionDescription)(pointer_to_free))
}

func (t _TransitionDescriptionTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*TransitionDescription)
	mem := (*C.lifecycle_msgs__msg__TransitionDescription)(dst)
	TransitionTypeSupport.AsCStruct(unsafe.Pointer(&mem.transition), &m.Transition)
	StateTypeSupport.AsCStruct(unsafe.Pointer(&mem.start_state), &m.StartState)
	StateTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal_state), &m.GoalState)
}

func (t _TransitionDescriptionTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*TransitionDescription)
	mem := (*C.lifecycle_msgs__msg__TransitionDescription)(ros2_message_buffer)
	TransitionTypeSupport.AsGoStruct(&m.Transition, unsafe.Pointer(&mem.transition))
	StateTypeSupport.AsGoStruct(&m.StartState, unsafe.Pointer(&mem.start_state))
	StateTypeSupport.AsGoStruct(&m.GoalState, unsafe.Pointer(&mem.goal_state))
}

func (t _TransitionDescriptionTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__lifecycle_msgs__msg__TransitionDescription())
}

type CTransitionDescription = C.lifecycle_msgs__msg__TransitionDescription
type CTransitionDescription__Sequence = C.lifecycle_msgs__msg__TransitionDescription__Sequence

func TransitionDescription__Sequence_to_Go(goSlice *[]TransitionDescription, cSlice CTransitionDescription__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]TransitionDescription, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		TransitionDescriptionTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func TransitionDescription__Sequence_to_C(cSlice *CTransitionDescription__Sequence, goSlice []TransitionDescription) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.lifecycle_msgs__msg__TransitionDescription)(C.malloc(C.sizeof_struct_lifecycle_msgs__msg__TransitionDescription * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		TransitionDescriptionTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func TransitionDescription__Array_to_Go(goSlice []TransitionDescription, cSlice []CTransitionDescription) {
	for i := 0; i < len(cSlice); i++ {
		TransitionDescriptionTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func TransitionDescription__Array_to_C(cSlice []CTransitionDescription, goSlice []TransitionDescription) {
	for i := 0; i < len(goSlice); i++ {
		TransitionDescriptionTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
