// Code generated by rclgo-gen. DO NOT EDIT.

package lifecycle_msgs_srv

import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <lifecycle_msgs/srv/change_state.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("lifecycle_msgs/ChangeState_Response", ChangeState_ResponseTypeSupport)
	typemap.RegisterMessage("lifecycle_msgs/srv/ChangeState_Response", ChangeState_ResponseTypeSupport)
}

type ChangeState_Response struct {
	Success bool `yaml:"success"` // Indicates whether the service was able to initiate the state transition
}

// NewChangeState_Response creates a new ChangeState_Response with default values.
func NewChangeState_Response() *ChangeState_Response {
	self := ChangeState_Response{}
	self.SetDefaults()
	return &self
}

func (t *ChangeState_Response) Clone() *ChangeState_Response {
	c := &ChangeState_Response{}
	c.Success = t.Success
	return c
}

func (t *ChangeState_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ChangeState_Response) SetDefaults() {
	t.Success = false
}

func (t *ChangeState_Response) GetTypeSupport() types.MessageTypeSupport {
	return ChangeState_ResponseTypeSupport
}

// ChangeState_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ChangeState_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewChangeState_ResponsePublisher creates and returns a new publisher for the
// ChangeState_Response
func NewChangeState_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ChangeState_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ChangeState_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ChangeState_ResponsePublisher{pub}, nil
}

func (p *ChangeState_ResponsePublisher) Publish(msg *ChangeState_Response) error {
	return p.Publisher.Publish(msg)
}

// ChangeState_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ChangeState_ResponseSubscription struct {
	*rclgo.Subscription
}

// ChangeState_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ChangeState_ResponseSubscription.
type ChangeState_ResponseSubscriptionCallback func(msg *ChangeState_Response, info *rclgo.MessageInfo, err error)

// NewChangeState_ResponseSubscription creates and returns a new subscription for the
// ChangeState_Response
func NewChangeState_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ChangeState_ResponseSubscriptionCallback) (*ChangeState_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ChangeState_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ChangeState_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ChangeState_ResponseSubscription{sub}, nil
}

func (s *ChangeState_ResponseSubscription) TakeMessage(out *ChangeState_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneChangeState_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneChangeState_ResponseSlice(dst, src []ChangeState_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ChangeState_ResponseTypeSupport types.MessageTypeSupport = _ChangeState_ResponseTypeSupport{}

type _ChangeState_ResponseTypeSupport struct{}

func (t _ChangeState_ResponseTypeSupport) New() types.Message {
	return NewChangeState_Response()
}

func (t _ChangeState_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.lifecycle_msgs__srv__ChangeState_Response
	return (unsafe.Pointer)(C.lifecycle_msgs__srv__ChangeState_Response__create())
}

func (t _ChangeState_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.lifecycle_msgs__srv__ChangeState_Response__destroy((*C.lifecycle_msgs__srv__ChangeState_Response)(pointer_to_free))
}

func (t _ChangeState_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ChangeState_Response)
	mem := (*C.lifecycle_msgs__srv__ChangeState_Response)(dst)
	mem.success = C.bool(m.Success)
}

func (t _ChangeState_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ChangeState_Response)
	mem := (*C.lifecycle_msgs__srv__ChangeState_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
}

func (t _ChangeState_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__lifecycle_msgs__srv__ChangeState_Response())
}

type CChangeState_Response = C.lifecycle_msgs__srv__ChangeState_Response
type CChangeState_Response__Sequence = C.lifecycle_msgs__srv__ChangeState_Response__Sequence

func ChangeState_Response__Sequence_to_Go(goSlice *[]ChangeState_Response, cSlice CChangeState_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ChangeState_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ChangeState_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ChangeState_Response__Sequence_to_C(cSlice *CChangeState_Response__Sequence, goSlice []ChangeState_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.lifecycle_msgs__srv__ChangeState_Response)(C.malloc(C.sizeof_struct_lifecycle_msgs__srv__ChangeState_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ChangeState_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ChangeState_Response__Array_to_Go(goSlice []ChangeState_Response, cSlice []CChangeState_Response) {
	for i := 0; i < len(cSlice); i++ {
		ChangeState_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ChangeState_Response__Array_to_C(cSlice []CChangeState_Response, goSlice []ChangeState_Response) {
	for i := 0; i < len(goSlice); i++ {
		ChangeState_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
