// Code generated by rclgo-gen. DO NOT EDIT.

package lifecycle_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <lifecycle_msgs/srv/get_available_states.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("lifecycle_msgs/GetAvailableStates", GetAvailableStatesTypeSupport)
	typemap.RegisterService("lifecycle_msgs/srv/GetAvailableStates", GetAvailableStatesTypeSupport)
}

type _GetAvailableStatesTypeSupport struct{}

func (s _GetAvailableStatesTypeSupport) Request() types.MessageTypeSupport {
	return GetAvailableStates_RequestTypeSupport
}

func (s _GetAvailableStatesTypeSupport) Response() types.MessageTypeSupport {
	return GetAvailableStates_ResponseTypeSupport
}

func (s _GetAvailableStatesTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__lifecycle_msgs__srv__GetAvailableStates())
}

// Modifying this variable is undefined behavior.
var GetAvailableStatesTypeSupport types.ServiceTypeSupport = _GetAvailableStatesTypeSupport{}

// GetAvailableStatesClient wraps rclgo.Client to provide type safe helper
// functions
type GetAvailableStatesClient struct {
	*rclgo.Client
}

// NewGetAvailableStatesClient creates and returns a new client for the
// GetAvailableStates
func NewGetAvailableStatesClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*GetAvailableStatesClient, error) {
	client, err := node.NewClient(serviceName, GetAvailableStatesTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetAvailableStatesClient{client}, nil
}

func (s *GetAvailableStatesClient) Send(ctx context.Context, req *GetAvailableStates_Request) (*GetAvailableStates_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetAvailableStates_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetAvailableStatesServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s GetAvailableStatesServiceResponseSender) SendResponse(resp *GetAvailableStates_Response) error {
	return s.sender.SendResponse(resp)
}

type GetAvailableStatesServiceRequestHandler func(*rclgo.ServiceInfo, *GetAvailableStates_Request, GetAvailableStatesServiceResponseSender)

// GetAvailableStatesService wraps rclgo.Service to provide type safe helper
// functions
type GetAvailableStatesService struct {
	*rclgo.Service
}

// NewGetAvailableStatesService creates and returns a new service for the
// GetAvailableStates
func NewGetAvailableStatesService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler GetAvailableStatesServiceRequestHandler) (*GetAvailableStatesService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*GetAvailableStates_Request)
		responseSender := GetAvailableStatesServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetAvailableStatesTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetAvailableStatesService{service}, nil
}
