// Code generated by rclgo-gen. DO NOT EDIT.

package lifecycle_msgs_srv

import (
	"unsafe"

	lifecycle_msgs_msg "github.com/merlindrones/rclgo/pkg/msgs/lifecycle_msgs/msg"
	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <lifecycle_msgs/srv/get_available_states.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("lifecycle_msgs/GetAvailableStates_Response", GetAvailableStates_ResponseTypeSupport)
	typemap.RegisterMessage("lifecycle_msgs/srv/GetAvailableStates_Response", GetAvailableStates_ResponseTypeSupport)
}

type GetAvailableStates_Response struct {
	AvailableStates []lifecycle_msgs_msg.State `yaml:"available_states"` // Array of possible states that can be transitioned to.
}

// NewGetAvailableStates_Response creates a new GetAvailableStates_Response with default values.
func NewGetAvailableStates_Response() *GetAvailableStates_Response {
	self := GetAvailableStates_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetAvailableStates_Response) Clone() *GetAvailableStates_Response {
	c := &GetAvailableStates_Response{}
	if t.AvailableStates != nil {
		c.AvailableStates = make([]lifecycle_msgs_msg.State, len(t.AvailableStates))
		lifecycle_msgs_msg.CloneStateSlice(c.AvailableStates, t.AvailableStates)
	}
	return c
}

func (t *GetAvailableStates_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetAvailableStates_Response) SetDefaults() {
	t.AvailableStates = nil
}

func (t *GetAvailableStates_Response) GetTypeSupport() types.MessageTypeSupport {
	return GetAvailableStates_ResponseTypeSupport
}

// GetAvailableStates_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetAvailableStates_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewGetAvailableStates_ResponsePublisher creates and returns a new publisher for the
// GetAvailableStates_Response
func NewGetAvailableStates_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetAvailableStates_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetAvailableStates_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetAvailableStates_ResponsePublisher{pub}, nil
}

func (p *GetAvailableStates_ResponsePublisher) Publish(msg *GetAvailableStates_Response) error {
	return p.Publisher.Publish(msg)
}

// GetAvailableStates_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetAvailableStates_ResponseSubscription struct {
	*rclgo.Subscription
}

// GetAvailableStates_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GetAvailableStates_ResponseSubscription.
type GetAvailableStates_ResponseSubscriptionCallback func(msg *GetAvailableStates_Response, info *rclgo.MessageInfo, err error)

// NewGetAvailableStates_ResponseSubscription creates and returns a new subscription for the
// GetAvailableStates_Response
func NewGetAvailableStates_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetAvailableStates_ResponseSubscriptionCallback) (*GetAvailableStates_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetAvailableStates_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetAvailableStates_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetAvailableStates_ResponseSubscription{sub}, nil
}

func (s *GetAvailableStates_ResponseSubscription) TakeMessage(out *GetAvailableStates_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetAvailableStates_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetAvailableStates_ResponseSlice(dst, src []GetAvailableStates_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetAvailableStates_ResponseTypeSupport types.MessageTypeSupport = _GetAvailableStates_ResponseTypeSupport{}

type _GetAvailableStates_ResponseTypeSupport struct{}

func (t _GetAvailableStates_ResponseTypeSupport) New() types.Message {
	return NewGetAvailableStates_Response()
}

func (t _GetAvailableStates_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.lifecycle_msgs__srv__GetAvailableStates_Response
	return (unsafe.Pointer)(C.lifecycle_msgs__srv__GetAvailableStates_Response__create())
}

func (t _GetAvailableStates_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.lifecycle_msgs__srv__GetAvailableStates_Response__destroy((*C.lifecycle_msgs__srv__GetAvailableStates_Response)(pointer_to_free))
}

func (t _GetAvailableStates_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetAvailableStates_Response)
	mem := (*C.lifecycle_msgs__srv__GetAvailableStates_Response)(dst)
	lifecycle_msgs_msg.State__Sequence_to_C((*lifecycle_msgs_msg.CState__Sequence)(unsafe.Pointer(&mem.available_states)), m.AvailableStates)
}

func (t _GetAvailableStates_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetAvailableStates_Response)
	mem := (*C.lifecycle_msgs__srv__GetAvailableStates_Response)(ros2_message_buffer)
	lifecycle_msgs_msg.State__Sequence_to_Go(&m.AvailableStates, *(*lifecycle_msgs_msg.CState__Sequence)(unsafe.Pointer(&mem.available_states)))
}

func (t _GetAvailableStates_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__lifecycle_msgs__srv__GetAvailableStates_Response())
}

type CGetAvailableStates_Response = C.lifecycle_msgs__srv__GetAvailableStates_Response
type CGetAvailableStates_Response__Sequence = C.lifecycle_msgs__srv__GetAvailableStates_Response__Sequence

func GetAvailableStates_Response__Sequence_to_Go(goSlice *[]GetAvailableStates_Response, cSlice CGetAvailableStates_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetAvailableStates_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetAvailableStates_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetAvailableStates_Response__Sequence_to_C(cSlice *CGetAvailableStates_Response__Sequence, goSlice []GetAvailableStates_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.lifecycle_msgs__srv__GetAvailableStates_Response)(C.malloc(C.sizeof_struct_lifecycle_msgs__srv__GetAvailableStates_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetAvailableStates_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetAvailableStates_Response__Array_to_Go(goSlice []GetAvailableStates_Response, cSlice []CGetAvailableStates_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetAvailableStates_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetAvailableStates_Response__Array_to_C(cSlice []CGetAvailableStates_Response, goSlice []GetAvailableStates_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetAvailableStates_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
