// Code generated by rclgo-gen. DO NOT EDIT.

package lifecycle_msgs_srv

import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <lifecycle_msgs/srv/get_available_states.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("lifecycle_msgs/GetAvailableStates_Request", GetAvailableStates_RequestTypeSupport)
	typemap.RegisterMessage("lifecycle_msgs/srv/GetAvailableStates_Request", GetAvailableStates_RequestTypeSupport)
}

type GetAvailableStates_Request struct {
}

// NewGetAvailableStates_Request creates a new GetAvailableStates_Request with default values.
func NewGetAvailableStates_Request() *GetAvailableStates_Request {
	self := GetAvailableStates_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetAvailableStates_Request) Clone() *GetAvailableStates_Request {
	c := &GetAvailableStates_Request{}
	return c
}

func (t *GetAvailableStates_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetAvailableStates_Request) SetDefaults() {
}

func (t *GetAvailableStates_Request) GetTypeSupport() types.MessageTypeSupport {
	return GetAvailableStates_RequestTypeSupport
}

// GetAvailableStates_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetAvailableStates_RequestPublisher struct {
	*rclgo.Publisher
}

// NewGetAvailableStates_RequestPublisher creates and returns a new publisher for the
// GetAvailableStates_Request
func NewGetAvailableStates_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetAvailableStates_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetAvailableStates_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetAvailableStates_RequestPublisher{pub}, nil
}

func (p *GetAvailableStates_RequestPublisher) Publish(msg *GetAvailableStates_Request) error {
	return p.Publisher.Publish(msg)
}

// GetAvailableStates_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetAvailableStates_RequestSubscription struct {
	*rclgo.Subscription
}

// GetAvailableStates_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a GetAvailableStates_RequestSubscription.
type GetAvailableStates_RequestSubscriptionCallback func(msg *GetAvailableStates_Request, info *rclgo.MessageInfo, err error)

// NewGetAvailableStates_RequestSubscription creates and returns a new subscription for the
// GetAvailableStates_Request
func NewGetAvailableStates_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetAvailableStates_RequestSubscriptionCallback) (*GetAvailableStates_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetAvailableStates_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetAvailableStates_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetAvailableStates_RequestSubscription{sub}, nil
}

func (s *GetAvailableStates_RequestSubscription) TakeMessage(out *GetAvailableStates_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetAvailableStates_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetAvailableStates_RequestSlice(dst, src []GetAvailableStates_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetAvailableStates_RequestTypeSupport types.MessageTypeSupport = _GetAvailableStates_RequestTypeSupport{}

type _GetAvailableStates_RequestTypeSupport struct{}

func (t _GetAvailableStates_RequestTypeSupport) New() types.Message {
	return NewGetAvailableStates_Request()
}

func (t _GetAvailableStates_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.lifecycle_msgs__srv__GetAvailableStates_Request
	return (unsafe.Pointer)(C.lifecycle_msgs__srv__GetAvailableStates_Request__create())
}

func (t _GetAvailableStates_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.lifecycle_msgs__srv__GetAvailableStates_Request__destroy((*C.lifecycle_msgs__srv__GetAvailableStates_Request)(pointer_to_free))
}

func (t _GetAvailableStates_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {

}

func (t _GetAvailableStates_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {

}

func (t _GetAvailableStates_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__lifecycle_msgs__srv__GetAvailableStates_Request())
}

type CGetAvailableStates_Request = C.lifecycle_msgs__srv__GetAvailableStates_Request
type CGetAvailableStates_Request__Sequence = C.lifecycle_msgs__srv__GetAvailableStates_Request__Sequence

func GetAvailableStates_Request__Sequence_to_Go(goSlice *[]GetAvailableStates_Request, cSlice CGetAvailableStates_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetAvailableStates_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetAvailableStates_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetAvailableStates_Request__Sequence_to_C(cSlice *CGetAvailableStates_Request__Sequence, goSlice []GetAvailableStates_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.lifecycle_msgs__srv__GetAvailableStates_Request)(C.malloc(C.sizeof_struct_lifecycle_msgs__srv__GetAvailableStates_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetAvailableStates_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetAvailableStates_Request__Array_to_Go(goSlice []GetAvailableStates_Request, cSlice []CGetAvailableStates_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetAvailableStates_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetAvailableStates_Request__Array_to_C(cSlice []CGetAvailableStates_Request, goSlice []GetAvailableStates_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetAvailableStates_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
