// Code generated by rclgo-gen. DO NOT EDIT.

package rcl_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rcl_interfaces/srv/describe_parameters.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rcl_interfaces/DescribeParameters", DescribeParametersTypeSupport)
	typemap.RegisterService("rcl_interfaces/srv/DescribeParameters", DescribeParametersTypeSupport)
}

type _DescribeParametersTypeSupport struct{}

func (s _DescribeParametersTypeSupport) Request() types.MessageTypeSupport {
	return DescribeParameters_RequestTypeSupport
}

func (s _DescribeParametersTypeSupport) Response() types.MessageTypeSupport {
	return DescribeParameters_ResponseTypeSupport
}

func (s _DescribeParametersTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rcl_interfaces__srv__DescribeParameters())
}

// Modifying this variable is undefined behavior.
var DescribeParametersTypeSupport types.ServiceTypeSupport = _DescribeParametersTypeSupport{}

// DescribeParametersClient wraps rclgo.Client to provide type safe helper
// functions
type DescribeParametersClient struct {
	*rclgo.Client
}

// NewDescribeParametersClient creates and returns a new client for the
// DescribeParameters
func NewDescribeParametersClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*DescribeParametersClient, error) {
	client, err := node.NewClient(serviceName, DescribeParametersTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &DescribeParametersClient{client}, nil
}

func (s *DescribeParametersClient) Send(ctx context.Context, req *DescribeParameters_Request) (*DescribeParameters_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*DescribeParameters_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type DescribeParametersServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s DescribeParametersServiceResponseSender) SendResponse(resp *DescribeParameters_Response) error {
	return s.sender.SendResponse(resp)
}

type DescribeParametersServiceRequestHandler func(*rclgo.ServiceInfo, *DescribeParameters_Request, DescribeParametersServiceResponseSender)

// DescribeParametersService wraps rclgo.Service to provide type safe helper
// functions
type DescribeParametersService struct {
	*rclgo.Service
}

// NewDescribeParametersService creates and returns a new service for the
// DescribeParameters
func NewDescribeParametersService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler DescribeParametersServiceRequestHandler) (*DescribeParametersService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*DescribeParameters_Request)
		responseSender := DescribeParametersServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, DescribeParametersTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &DescribeParametersService{service}, nil
}
