// Code generated by rclgo-gen. DO NOT EDIT.

package rcl_interfaces_srv

import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	primitives "github.com/merlindrones/rclgo/pkg/rclgo/primitives"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rcl_interfaces/srv/get_parameters.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rcl_interfaces/GetParameters_Request", GetParameters_RequestTypeSupport)
	typemap.RegisterMessage("rcl_interfaces/srv/GetParameters_Request", GetParameters_RequestTypeSupport)
}

type GetParameters_Request struct {
	Names []string `yaml:"names"` // A list of parameter names to get.
}

// NewGetParameters_Request creates a new GetParameters_Request with default values.
func NewGetParameters_Request() *GetParameters_Request {
	self := GetParameters_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetParameters_Request) Clone() *GetParameters_Request {
	c := &GetParameters_Request{}
	if t.Names != nil {
		c.Names = make([]string, len(t.Names))
		copy(c.Names, t.Names)
	}
	return c
}

func (t *GetParameters_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetParameters_Request) SetDefaults() {
	t.Names = nil
}

func (t *GetParameters_Request) GetTypeSupport() types.MessageTypeSupport {
	return GetParameters_RequestTypeSupport
}

// GetParameters_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetParameters_RequestPublisher struct {
	*rclgo.Publisher
}

// NewGetParameters_RequestPublisher creates and returns a new publisher for the
// GetParameters_Request
func NewGetParameters_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetParameters_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetParameters_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetParameters_RequestPublisher{pub}, nil
}

func (p *GetParameters_RequestPublisher) Publish(msg *GetParameters_Request) error {
	return p.Publisher.Publish(msg)
}

// GetParameters_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetParameters_RequestSubscription struct {
	*rclgo.Subscription
}

// GetParameters_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a GetParameters_RequestSubscription.
type GetParameters_RequestSubscriptionCallback func(msg *GetParameters_Request, info *rclgo.MessageInfo, err error)

// NewGetParameters_RequestSubscription creates and returns a new subscription for the
// GetParameters_Request
func NewGetParameters_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetParameters_RequestSubscriptionCallback) (*GetParameters_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetParameters_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetParameters_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetParameters_RequestSubscription{sub}, nil
}

func (s *GetParameters_RequestSubscription) TakeMessage(out *GetParameters_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetParameters_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetParameters_RequestSlice(dst, src []GetParameters_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetParameters_RequestTypeSupport types.MessageTypeSupport = _GetParameters_RequestTypeSupport{}

type _GetParameters_RequestTypeSupport struct{}

func (t _GetParameters_RequestTypeSupport) New() types.Message {
	return NewGetParameters_Request()
}

func (t _GetParameters_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rcl_interfaces__srv__GetParameters_Request
	return (unsafe.Pointer)(C.rcl_interfaces__srv__GetParameters_Request__create())
}

func (t _GetParameters_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rcl_interfaces__srv__GetParameters_Request__destroy((*C.rcl_interfaces__srv__GetParameters_Request)(pointer_to_free))
}

func (t _GetParameters_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetParameters_Request)
	mem := (*C.rcl_interfaces__srv__GetParameters_Request)(dst)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.names)), m.Names)
}

func (t _GetParameters_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetParameters_Request)
	mem := (*C.rcl_interfaces__srv__GetParameters_Request)(ros2_message_buffer)
	primitives.String__Sequence_to_Go(&m.Names, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.names)))
}

func (t _GetParameters_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rcl_interfaces__srv__GetParameters_Request())
}

type CGetParameters_Request = C.rcl_interfaces__srv__GetParameters_Request
type CGetParameters_Request__Sequence = C.rcl_interfaces__srv__GetParameters_Request__Sequence

func GetParameters_Request__Sequence_to_Go(goSlice *[]GetParameters_Request, cSlice CGetParameters_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetParameters_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetParameters_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetParameters_Request__Sequence_to_C(cSlice *CGetParameters_Request__Sequence, goSlice []GetParameters_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rcl_interfaces__srv__GetParameters_Request)(C.malloc(C.sizeof_struct_rcl_interfaces__srv__GetParameters_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetParameters_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetParameters_Request__Array_to_Go(goSlice []GetParameters_Request, cSlice []CGetParameters_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetParameters_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetParameters_Request__Array_to_C(cSlice []CGetParameters_Request, goSlice []GetParameters_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetParameters_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
