// Code generated by rclgo-gen. DO NOT EDIT.

package rcl_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rcl_interfaces/srv/get_parameters.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rcl_interfaces/GetParameters", GetParametersTypeSupport)
	typemap.RegisterService("rcl_interfaces/srv/GetParameters", GetParametersTypeSupport)
}

type _GetParametersTypeSupport struct{}

func (s _GetParametersTypeSupport) Request() types.MessageTypeSupport {
	return GetParameters_RequestTypeSupport
}

func (s _GetParametersTypeSupport) Response() types.MessageTypeSupport {
	return GetParameters_ResponseTypeSupport
}

func (s _GetParametersTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rcl_interfaces__srv__GetParameters())
}

// Modifying this variable is undefined behavior.
var GetParametersTypeSupport types.ServiceTypeSupport = _GetParametersTypeSupport{}

// GetParametersClient wraps rclgo.Client to provide type safe helper
// functions
type GetParametersClient struct {
	*rclgo.Client
}

// NewGetParametersClient creates and returns a new client for the
// GetParameters
func NewGetParametersClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*GetParametersClient, error) {
	client, err := node.NewClient(serviceName, GetParametersTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetParametersClient{client}, nil
}

func (s *GetParametersClient) Send(ctx context.Context, req *GetParameters_Request) (*GetParameters_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetParameters_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetParametersServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s GetParametersServiceResponseSender) SendResponse(resp *GetParameters_Response) error {
	return s.sender.SendResponse(resp)
}

type GetParametersServiceRequestHandler func(*rclgo.ServiceInfo, *GetParameters_Request, GetParametersServiceResponseSender)

// GetParametersService wraps rclgo.Service to provide type safe helper
// functions
type GetParametersService struct {
	*rclgo.Service
}

// NewGetParametersService creates and returns a new service for the
// GetParameters
func NewGetParametersService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler GetParametersServiceRequestHandler) (*GetParametersService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*GetParameters_Request)
		responseSender := GetParametersServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetParametersTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetParametersService{service}, nil
}
