// Code generated by rclgo-gen. DO NOT EDIT.

package rcl_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rcl_interfaces/srv/get_parameter_types.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rcl_interfaces/GetParameterTypes", GetParameterTypesTypeSupport)
	typemap.RegisterService("rcl_interfaces/srv/GetParameterTypes", GetParameterTypesTypeSupport)
}

type _GetParameterTypesTypeSupport struct{}

func (s _GetParameterTypesTypeSupport) Request() types.MessageTypeSupport {
	return GetParameterTypes_RequestTypeSupport
}

func (s _GetParameterTypesTypeSupport) Response() types.MessageTypeSupport {
	return GetParameterTypes_ResponseTypeSupport
}

func (s _GetParameterTypesTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rcl_interfaces__srv__GetParameterTypes())
}

// Modifying this variable is undefined behavior.
var GetParameterTypesTypeSupport types.ServiceTypeSupport = _GetParameterTypesTypeSupport{}

// GetParameterTypesClient wraps rclgo.Client to provide type safe helper
// functions
type GetParameterTypesClient struct {
	*rclgo.Client
}

// NewGetParameterTypesClient creates and returns a new client for the
// GetParameterTypes
func NewGetParameterTypesClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*GetParameterTypesClient, error) {
	client, err := node.NewClient(serviceName, GetParameterTypesTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetParameterTypesClient{client}, nil
}

func (s *GetParameterTypesClient) Send(ctx context.Context, req *GetParameterTypes_Request) (*GetParameterTypes_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetParameterTypes_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetParameterTypesServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s GetParameterTypesServiceResponseSender) SendResponse(resp *GetParameterTypes_Response) error {
	return s.sender.SendResponse(resp)
}

type GetParameterTypesServiceRequestHandler func(*rclgo.ServiceInfo, *GetParameterTypes_Request, GetParameterTypesServiceResponseSender)

// GetParameterTypesService wraps rclgo.Service to provide type safe helper
// functions
type GetParameterTypesService struct {
	*rclgo.Service
}

// NewGetParameterTypesService creates and returns a new service for the
// GetParameterTypes
func NewGetParameterTypesService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler GetParameterTypesServiceRequestHandler) (*GetParameterTypesService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*GetParameterTypes_Request)
		responseSender := GetParameterTypesServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetParameterTypesTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetParameterTypesService{service}, nil
}
