// Code generated by rclgo-gen. DO NOT EDIT.

package rcl_interfaces_srv

import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	primitives "github.com/merlindrones/rclgo/pkg/rclgo/primitives"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rcl_interfaces/srv/get_parameter_types.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rcl_interfaces/GetParameterTypes_Request", GetParameterTypes_RequestTypeSupport)
	typemap.RegisterMessage("rcl_interfaces/srv/GetParameterTypes_Request", GetParameterTypes_RequestTypeSupport)
}

type GetParameterTypes_Request struct {
	Names []string `yaml:"names"` // A list of parameter names.TODO(wjwwood): link to parameter naming rules.
}

// NewGetParameterTypes_Request creates a new GetParameterTypes_Request with default values.
func NewGetParameterTypes_Request() *GetParameterTypes_Request {
	self := GetParameterTypes_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetParameterTypes_Request) Clone() *GetParameterTypes_Request {
	c := &GetParameterTypes_Request{}
	if t.Names != nil {
		c.Names = make([]string, len(t.Names))
		copy(c.Names, t.Names)
	}
	return c
}

func (t *GetParameterTypes_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetParameterTypes_Request) SetDefaults() {
	t.Names = nil
}

func (t *GetParameterTypes_Request) GetTypeSupport() types.MessageTypeSupport {
	return GetParameterTypes_RequestTypeSupport
}

// GetParameterTypes_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetParameterTypes_RequestPublisher struct {
	*rclgo.Publisher
}

// NewGetParameterTypes_RequestPublisher creates and returns a new publisher for the
// GetParameterTypes_Request
func NewGetParameterTypes_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetParameterTypes_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetParameterTypes_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetParameterTypes_RequestPublisher{pub}, nil
}

func (p *GetParameterTypes_RequestPublisher) Publish(msg *GetParameterTypes_Request) error {
	return p.Publisher.Publish(msg)
}

// GetParameterTypes_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetParameterTypes_RequestSubscription struct {
	*rclgo.Subscription
}

// GetParameterTypes_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a GetParameterTypes_RequestSubscription.
type GetParameterTypes_RequestSubscriptionCallback func(msg *GetParameterTypes_Request, info *rclgo.MessageInfo, err error)

// NewGetParameterTypes_RequestSubscription creates and returns a new subscription for the
// GetParameterTypes_Request
func NewGetParameterTypes_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetParameterTypes_RequestSubscriptionCallback) (*GetParameterTypes_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetParameterTypes_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetParameterTypes_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetParameterTypes_RequestSubscription{sub}, nil
}

func (s *GetParameterTypes_RequestSubscription) TakeMessage(out *GetParameterTypes_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetParameterTypes_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetParameterTypes_RequestSlice(dst, src []GetParameterTypes_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetParameterTypes_RequestTypeSupport types.MessageTypeSupport = _GetParameterTypes_RequestTypeSupport{}

type _GetParameterTypes_RequestTypeSupport struct{}

func (t _GetParameterTypes_RequestTypeSupport) New() types.Message {
	return NewGetParameterTypes_Request()
}

func (t _GetParameterTypes_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rcl_interfaces__srv__GetParameterTypes_Request
	return (unsafe.Pointer)(C.rcl_interfaces__srv__GetParameterTypes_Request__create())
}

func (t _GetParameterTypes_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rcl_interfaces__srv__GetParameterTypes_Request__destroy((*C.rcl_interfaces__srv__GetParameterTypes_Request)(pointer_to_free))
}

func (t _GetParameterTypes_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetParameterTypes_Request)
	mem := (*C.rcl_interfaces__srv__GetParameterTypes_Request)(dst)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.names)), m.Names)
}

func (t _GetParameterTypes_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetParameterTypes_Request)
	mem := (*C.rcl_interfaces__srv__GetParameterTypes_Request)(ros2_message_buffer)
	primitives.String__Sequence_to_Go(&m.Names, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.names)))
}

func (t _GetParameterTypes_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rcl_interfaces__srv__GetParameterTypes_Request())
}

type CGetParameterTypes_Request = C.rcl_interfaces__srv__GetParameterTypes_Request
type CGetParameterTypes_Request__Sequence = C.rcl_interfaces__srv__GetParameterTypes_Request__Sequence

func GetParameterTypes_Request__Sequence_to_Go(goSlice *[]GetParameterTypes_Request, cSlice CGetParameterTypes_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetParameterTypes_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetParameterTypes_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetParameterTypes_Request__Sequence_to_C(cSlice *CGetParameterTypes_Request__Sequence, goSlice []GetParameterTypes_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rcl_interfaces__srv__GetParameterTypes_Request)(C.malloc(C.sizeof_struct_rcl_interfaces__srv__GetParameterTypes_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetParameterTypes_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetParameterTypes_Request__Array_to_Go(goSlice []GetParameterTypes_Request, cSlice []CGetParameterTypes_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetParameterTypes_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetParameterTypes_Request__Array_to_C(cSlice []CGetParameterTypes_Request, goSlice []GetParameterTypes_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetParameterTypes_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
