// Code generated by rclgo-gen. DO NOT EDIT.

package rcl_interfaces_srv

import (
	"unsafe"

	rcl_interfaces_msg "github.com/merlindrones/rclgo/pkg/msgs/rcl_interfaces/msg"
	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rcl_interfaces/srv/get_parameters.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rcl_interfaces/GetParameters_Response", GetParameters_ResponseTypeSupport)
	typemap.RegisterMessage("rcl_interfaces/srv/GetParameters_Response", GetParameters_ResponseTypeSupport)
}

type GetParameters_Response struct {
	Values []rcl_interfaces_msg.ParameterValue `yaml:"values"` // List of values which is the same length and order as the provided names. If aparameter was not yet set, the value will have PARAMETER_NOT_SET as thetype.
}

// NewGetParameters_Response creates a new GetParameters_Response with default values.
func NewGetParameters_Response() *GetParameters_Response {
	self := GetParameters_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetParameters_Response) Clone() *GetParameters_Response {
	c := &GetParameters_Response{}
	if t.Values != nil {
		c.Values = make([]rcl_interfaces_msg.ParameterValue, len(t.Values))
		rcl_interfaces_msg.CloneParameterValueSlice(c.Values, t.Values)
	}
	return c
}

func (t *GetParameters_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetParameters_Response) SetDefaults() {
	t.Values = nil
}

func (t *GetParameters_Response) GetTypeSupport() types.MessageTypeSupport {
	return GetParameters_ResponseTypeSupport
}

// GetParameters_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetParameters_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewGetParameters_ResponsePublisher creates and returns a new publisher for the
// GetParameters_Response
func NewGetParameters_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetParameters_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetParameters_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetParameters_ResponsePublisher{pub}, nil
}

func (p *GetParameters_ResponsePublisher) Publish(msg *GetParameters_Response) error {
	return p.Publisher.Publish(msg)
}

// GetParameters_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetParameters_ResponseSubscription struct {
	*rclgo.Subscription
}

// GetParameters_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GetParameters_ResponseSubscription.
type GetParameters_ResponseSubscriptionCallback func(msg *GetParameters_Response, info *rclgo.MessageInfo, err error)

// NewGetParameters_ResponseSubscription creates and returns a new subscription for the
// GetParameters_Response
func NewGetParameters_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetParameters_ResponseSubscriptionCallback) (*GetParameters_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetParameters_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetParameters_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetParameters_ResponseSubscription{sub}, nil
}

func (s *GetParameters_ResponseSubscription) TakeMessage(out *GetParameters_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetParameters_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetParameters_ResponseSlice(dst, src []GetParameters_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetParameters_ResponseTypeSupport types.MessageTypeSupport = _GetParameters_ResponseTypeSupport{}

type _GetParameters_ResponseTypeSupport struct{}

func (t _GetParameters_ResponseTypeSupport) New() types.Message {
	return NewGetParameters_Response()
}

func (t _GetParameters_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rcl_interfaces__srv__GetParameters_Response
	return (unsafe.Pointer)(C.rcl_interfaces__srv__GetParameters_Response__create())
}

func (t _GetParameters_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rcl_interfaces__srv__GetParameters_Response__destroy((*C.rcl_interfaces__srv__GetParameters_Response)(pointer_to_free))
}

func (t _GetParameters_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetParameters_Response)
	mem := (*C.rcl_interfaces__srv__GetParameters_Response)(dst)
	rcl_interfaces_msg.ParameterValue__Sequence_to_C((*rcl_interfaces_msg.CParameterValue__Sequence)(unsafe.Pointer(&mem.values)), m.Values)
}

func (t _GetParameters_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetParameters_Response)
	mem := (*C.rcl_interfaces__srv__GetParameters_Response)(ros2_message_buffer)
	rcl_interfaces_msg.ParameterValue__Sequence_to_Go(&m.Values, *(*rcl_interfaces_msg.CParameterValue__Sequence)(unsafe.Pointer(&mem.values)))
}

func (t _GetParameters_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rcl_interfaces__srv__GetParameters_Response())
}

type CGetParameters_Response = C.rcl_interfaces__srv__GetParameters_Response
type CGetParameters_Response__Sequence = C.rcl_interfaces__srv__GetParameters_Response__Sequence

func GetParameters_Response__Sequence_to_Go(goSlice *[]GetParameters_Response, cSlice CGetParameters_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetParameters_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetParameters_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetParameters_Response__Sequence_to_C(cSlice *CGetParameters_Response__Sequence, goSlice []GetParameters_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rcl_interfaces__srv__GetParameters_Response)(C.malloc(C.sizeof_struct_rcl_interfaces__srv__GetParameters_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetParameters_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetParameters_Response__Array_to_Go(goSlice []GetParameters_Response, cSlice []CGetParameters_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetParameters_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetParameters_Response__Array_to_C(cSlice []CGetParameters_Response, goSlice []GetParameters_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetParameters_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
