// Code generated by rclgo-gen. DO NOT EDIT.

package rcl_interfaces_srv

import (
	"unsafe"

	rcl_interfaces_msg "github.com/merlindrones/rclgo/pkg/msgs/rcl_interfaces/msg"
	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rcl_interfaces/srv/set_parameters.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rcl_interfaces/SetParameters_Response", SetParameters_ResponseTypeSupport)
	typemap.RegisterMessage("rcl_interfaces/srv/SetParameters_Response", SetParameters_ResponseTypeSupport)
}

type SetParameters_Response struct {
	Results []rcl_interfaces_msg.SetParametersResult `yaml:"results"` // Indicates whether setting each parameter succeeded or not and why.
}

// NewSetParameters_Response creates a new SetParameters_Response with default values.
func NewSetParameters_Response() *SetParameters_Response {
	self := SetParameters_Response{}
	self.SetDefaults()
	return &self
}

func (t *SetParameters_Response) Clone() *SetParameters_Response {
	c := &SetParameters_Response{}
	if t.Results != nil {
		c.Results = make([]rcl_interfaces_msg.SetParametersResult, len(t.Results))
		rcl_interfaces_msg.CloneSetParametersResultSlice(c.Results, t.Results)
	}
	return c
}

func (t *SetParameters_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetParameters_Response) SetDefaults() {
	t.Results = nil
}

func (t *SetParameters_Response) GetTypeSupport() types.MessageTypeSupport {
	return SetParameters_ResponseTypeSupport
}

// SetParameters_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SetParameters_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewSetParameters_ResponsePublisher creates and returns a new publisher for the
// SetParameters_Response
func NewSetParameters_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SetParameters_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, SetParameters_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetParameters_ResponsePublisher{pub}, nil
}

func (p *SetParameters_ResponsePublisher) Publish(msg *SetParameters_Response) error {
	return p.Publisher.Publish(msg)
}

// SetParameters_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SetParameters_ResponseSubscription struct {
	*rclgo.Subscription
}

// SetParameters_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a SetParameters_ResponseSubscription.
type SetParameters_ResponseSubscriptionCallback func(msg *SetParameters_Response, info *rclgo.MessageInfo, err error)

// NewSetParameters_ResponseSubscription creates and returns a new subscription for the
// SetParameters_Response
func NewSetParameters_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SetParameters_ResponseSubscriptionCallback) (*SetParameters_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SetParameters_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SetParameters_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SetParameters_ResponseSubscription{sub}, nil
}

func (s *SetParameters_ResponseSubscription) TakeMessage(out *SetParameters_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSetParameters_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetParameters_ResponseSlice(dst, src []SetParameters_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetParameters_ResponseTypeSupport types.MessageTypeSupport = _SetParameters_ResponseTypeSupport{}

type _SetParameters_ResponseTypeSupport struct{}

func (t _SetParameters_ResponseTypeSupport) New() types.Message {
	return NewSetParameters_Response()
}

func (t _SetParameters_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rcl_interfaces__srv__SetParameters_Response
	return (unsafe.Pointer)(C.rcl_interfaces__srv__SetParameters_Response__create())
}

func (t _SetParameters_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rcl_interfaces__srv__SetParameters_Response__destroy((*C.rcl_interfaces__srv__SetParameters_Response)(pointer_to_free))
}

func (t _SetParameters_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetParameters_Response)
	mem := (*C.rcl_interfaces__srv__SetParameters_Response)(dst)
	rcl_interfaces_msg.SetParametersResult__Sequence_to_C((*rcl_interfaces_msg.CSetParametersResult__Sequence)(unsafe.Pointer(&mem.results)), m.Results)
}

func (t _SetParameters_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetParameters_Response)
	mem := (*C.rcl_interfaces__srv__SetParameters_Response)(ros2_message_buffer)
	rcl_interfaces_msg.SetParametersResult__Sequence_to_Go(&m.Results, *(*rcl_interfaces_msg.CSetParametersResult__Sequence)(unsafe.Pointer(&mem.results)))
}

func (t _SetParameters_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rcl_interfaces__srv__SetParameters_Response())
}

type CSetParameters_Response = C.rcl_interfaces__srv__SetParameters_Response
type CSetParameters_Response__Sequence = C.rcl_interfaces__srv__SetParameters_Response__Sequence

func SetParameters_Response__Sequence_to_Go(goSlice *[]SetParameters_Response, cSlice CSetParameters_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetParameters_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SetParameters_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SetParameters_Response__Sequence_to_C(cSlice *CSetParameters_Response__Sequence, goSlice []SetParameters_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rcl_interfaces__srv__SetParameters_Response)(C.malloc(C.sizeof_struct_rcl_interfaces__srv__SetParameters_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SetParameters_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SetParameters_Response__Array_to_Go(goSlice []SetParameters_Response, cSlice []CSetParameters_Response) {
	for i := 0; i < len(cSlice); i++ {
		SetParameters_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetParameters_Response__Array_to_C(cSlice []CSetParameters_Response, goSlice []SetParameters_Response) {
	for i := 0; i < len(goSlice); i++ {
		SetParameters_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
