// Code generated by shimgen; DO NOT EDIT.
// Deprecated: use github.com/merlindrones/rclgo/pkg/msgs/rosgraph_msgs/msg instead.
package msg

import pub "github.com/merlindrones/rclgo/pkg/msgs/rosgraph_msgs/msg"

type CClock = pub.CClock
type CClock__Sequence = pub.CClock__Sequence
type Clock = pub.Clock
type ClockPublisher = pub.ClockPublisher
type ClockSubscription = pub.ClockSubscription
type ClockSubscriptionCallback = pub.ClockSubscriptionCallback

var ClockTypeSupport = pub.ClockTypeSupport

var Clock__Array_to_C = pub.Clock__Array_to_C
var Clock__Array_to_Go = pub.Clock__Array_to_Go
var Clock__Sequence_to_C = pub.Clock__Sequence_to_C
var Clock__Sequence_to_Go = pub.Clock__Sequence_to_Go
var CloneClockSlice = pub.CloneClockSlice
var NewClock = pub.NewClock
var NewClockPublisher = pub.NewClockPublisher
var NewClockSubscription = pub.NewClockSubscription
