// Code generated by rclgo-gen. DO NOT EDIT.

package geometry_msgs_msg

import (
	"unsafe"

	std_msgs_msg "github.com/merlindrones/rclgo/pkg/msgs/std_msgs/msg"
	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geometry_msgs/msg/polygon_instance_stamped.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geometry_msgs/PolygonInstanceStamped", PolygonInstanceStampedTypeSupport)
	typemap.RegisterMessage("geometry_msgs/msg/PolygonInstanceStamped", PolygonInstanceStampedTypeSupport)
}

type PolygonInstanceStamped struct {
	Header  std_msgs_msg.Header `yaml:"header"`
	Polygon PolygonInstance     `yaml:"polygon"`
}

// NewPolygonInstanceStamped creates a new PolygonInstanceStamped with default values.
func NewPolygonInstanceStamped() *PolygonInstanceStamped {
	self := PolygonInstanceStamped{}
	self.SetDefaults()
	return &self
}

func (t *PolygonInstanceStamped) Clone() *PolygonInstanceStamped {
	c := &PolygonInstanceStamped{}
	c.Header = *t.Header.Clone()
	c.Polygon = *t.Polygon.Clone()
	return c
}

func (t *PolygonInstanceStamped) CloneMsg() types.Message {
	return t.Clone()
}

func (t *PolygonInstanceStamped) SetDefaults() {
	t.Header.SetDefaults()
	t.Polygon.SetDefaults()
}

func (t *PolygonInstanceStamped) GetTypeSupport() types.MessageTypeSupport {
	return PolygonInstanceStampedTypeSupport
}

// PolygonInstanceStampedPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type PolygonInstanceStampedPublisher struct {
	*rclgo.Publisher
}

// NewPolygonInstanceStampedPublisher creates and returns a new publisher for the
// PolygonInstanceStamped
func NewPolygonInstanceStampedPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*PolygonInstanceStampedPublisher, error) {
	pub, err := node.NewPublisher(topic_name, PolygonInstanceStampedTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &PolygonInstanceStampedPublisher{pub}, nil
}

func (p *PolygonInstanceStampedPublisher) Publish(msg *PolygonInstanceStamped) error {
	return p.Publisher.Publish(msg)
}

// PolygonInstanceStampedSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type PolygonInstanceStampedSubscription struct {
	*rclgo.Subscription
}

// PolygonInstanceStampedSubscriptionCallback type is used to provide a subscription
// handler function for a PolygonInstanceStampedSubscription.
type PolygonInstanceStampedSubscriptionCallback func(msg *PolygonInstanceStamped, info *rclgo.MessageInfo, err error)

// NewPolygonInstanceStampedSubscription creates and returns a new subscription for the
// PolygonInstanceStamped
func NewPolygonInstanceStampedSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback PolygonInstanceStampedSubscriptionCallback) (*PolygonInstanceStampedSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg PolygonInstanceStamped
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, PolygonInstanceStampedTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &PolygonInstanceStampedSubscription{sub}, nil
}

func (s *PolygonInstanceStampedSubscription) TakeMessage(out *PolygonInstanceStamped) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// ClonePolygonInstanceStampedSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePolygonInstanceStampedSlice(dst, src []PolygonInstanceStamped) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var PolygonInstanceStampedTypeSupport types.MessageTypeSupport = _PolygonInstanceStampedTypeSupport{}

type _PolygonInstanceStampedTypeSupport struct{}

func (t _PolygonInstanceStampedTypeSupport) New() types.Message {
	return NewPolygonInstanceStamped()
}

func (t _PolygonInstanceStampedTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geometry_msgs__msg__PolygonInstanceStamped
	return (unsafe.Pointer)(C.geometry_msgs__msg__PolygonInstanceStamped__create())
}

func (t _PolygonInstanceStampedTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geometry_msgs__msg__PolygonInstanceStamped__destroy((*C.geometry_msgs__msg__PolygonInstanceStamped)(pointer_to_free))
}

func (t _PolygonInstanceStampedTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*PolygonInstanceStamped)
	mem := (*C.geometry_msgs__msg__PolygonInstanceStamped)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	PolygonInstanceTypeSupport.AsCStruct(unsafe.Pointer(&mem.polygon), &m.Polygon)
}

func (t _PolygonInstanceStampedTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*PolygonInstanceStamped)
	mem := (*C.geometry_msgs__msg__PolygonInstanceStamped)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	PolygonInstanceTypeSupport.AsGoStruct(&m.Polygon, unsafe.Pointer(&mem.polygon))
}

func (t _PolygonInstanceStampedTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geometry_msgs__msg__PolygonInstanceStamped())
}

type CPolygonInstanceStamped = C.geometry_msgs__msg__PolygonInstanceStamped
type CPolygonInstanceStamped__Sequence = C.geometry_msgs__msg__PolygonInstanceStamped__Sequence

func PolygonInstanceStamped__Sequence_to_Go(goSlice *[]PolygonInstanceStamped, cSlice CPolygonInstanceStamped__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]PolygonInstanceStamped, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		PolygonInstanceStampedTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func PolygonInstanceStamped__Sequence_to_C(cSlice *CPolygonInstanceStamped__Sequence, goSlice []PolygonInstanceStamped) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.geometry_msgs__msg__PolygonInstanceStamped)(C.malloc(C.sizeof_struct_geometry_msgs__msg__PolygonInstanceStamped * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		PolygonInstanceStampedTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func PolygonInstanceStamped__Array_to_Go(goSlice []PolygonInstanceStamped, cSlice []CPolygonInstanceStamped) {
	for i := 0; i < len(cSlice); i++ {
		PolygonInstanceStampedTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func PolygonInstanceStamped__Array_to_C(cSlice []CPolygonInstanceStamped, goSlice []PolygonInstanceStamped) {
	for i := 0; i < len(goSlice); i++ {
		PolygonInstanceStampedTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
