// Code generated by rclgo-gen. DO NOT EDIT.

package rclgo

/*
#cgo LDFLAGS: "-L/opt/ros/humble/lib" "-Wl,-rpath=/opt/ros/humble/lib"
#cgo CFLAGS: "-I/opt/ros/humble/include/action_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/builtin_interfaces"
#cgo CFLAGS: "-I/opt/ros/humble/include/rcl"
#cgo CFLAGS: "-I/opt/ros/humble/include/rcutils"
#cgo CFLAGS: "-I/opt/ros/humble/include/rcl_action"
#cgo CFLAGS: "-I/opt/ros/humble/include/rcl_yaml_param_parser"
#cgo CFLAGS: "-I/opt/ros/humble/include/rmw"
#cgo CFLAGS: "-I/opt/ros/humble/include/rosidl_dynamic_typesupport"
#cgo CFLAGS: "-I/opt/ros/humble/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/opt/ros/humble/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/opt/ros/humble/include/service_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/type_description_interfaces"
#cgo CFLAGS: "-I/opt/ros/humble/include/unique_identifier_msgs"

#cgo LDFLAGS: "-L/home/dave/Git/merlin/rclgo/lib" "-Wl,-rpath=/home/dave/Git/merlin/rclgo/lib"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/action_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/builtin_interfaces"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/rcl"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/rcutils"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/rcl_action"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/rcl_yaml_param_parser"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/rmw"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/rosidl_dynamic_typesupport"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/service_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/type_description_interfaces"
#cgo CFLAGS: "-I/home/dave/Git/merlin/rclgo/include/unique_identifier_msgs"

#cgo LDFLAGS: -lrcl -lrmw -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrcl_action -lrmw_implementation
*/
import "C"
