// Code generated by shimgen; DO NOT EDIT.
// Deprecated: use github.com/merlindrones/rclgo/pkg/msgs/unique_identifier_msgs/msg instead.
package msg

import pub "github.com/merlindrones/rclgo/pkg/msgs/unique_identifier_msgs/msg"

type CUUID = pub.CUUID
type CUUID__Sequence = pub.CUUID__Sequence
type UUID = pub.UUID
type UUIDPublisher = pub.UUIDPublisher
type UUIDSubscription = pub.UUIDSubscription
type UUIDSubscriptionCallback = pub.UUIDSubscriptionCallback

var UUIDTypeSupport = pub.UUIDTypeSupport

var CloneUUIDSlice = pub.CloneUUIDSlice
var NewUUID = pub.NewUUID
var NewUUIDPublisher = pub.NewUUIDPublisher
var NewUUIDSubscription = pub.NewUUIDSubscription
var UUID__Array_to_C = pub.UUID__Array_to_C
var UUID__Array_to_Go = pub.UUID__Array_to_Go
var UUID__Sequence_to_C = pub.UUID__Sequence_to_C
var UUID__Sequence_to_Go = pub.UUID__Sequence_to_Go
