// Code generated by rclgo-gen. DO NOT EDIT.

package unique_identifier_msgs_msg

/*
#cgo LDFLAGS: "-L/opt/ros/humble/lib" "-Wl,-rpath=/opt/ros/humble/lib"

#cgo LDFLAGS: -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lunique_identifier_msgs__rosidl_typesupport_c -lunique_identifier_msgs__rosidl_generator_c

#cgo CFLAGS: "-I/opt/ros/humble/include/action_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/builtin_interfaces"
#cgo CFLAGS: "-I/opt/ros/humble/include/example_interfaces"
#cgo CFLAGS: "-I/opt/ros/humble/include/geometry_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/rcutils"
#cgo CFLAGS: "-I/opt/ros/humble/include/rosidl_dynamic_typesupport"
#cgo CFLAGS: "-I/opt/ros/humble/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/opt/ros/humble/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/opt/ros/humble/include/sensor_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/service_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/std_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/std_srvs"
#cgo CFLAGS: "-I/opt/ros/humble/include/test_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/type_description_interfaces"
#cgo CFLAGS: "-I/opt/ros/humble/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/unique_identifier_msgs"
*/
import "C"
